apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exposecontroller
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: exposecontroller
    spec:
      serviceAccountName: exposecontroller
      containers:
      - name: exposecontroller
        image: olliai/exposecontroller:latest
        ports:
        - name: health
          containerPort: 10254
        readinessProbe:
          httpGet:
            path: /healthz
            port: health
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
