kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exposecontroller
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "update"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "create", "update", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exposecontroller
roleRef:
  kind: ClusterRole
  name: exposecontroller
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: exposecontroller
    namespace: kube-system
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: exposecontroller
  namespace: kube-system
