apiVersion: v1
appVersion: v2.0.0
name: exposecontroller
description: Controller for automatically exposing services. A more stable version of Jenkins-X exposecontroller.
version: 2.0.0
home: https://github.com/devopscare/exposecontroller
sources:
- https://github.com/devopscare/exposecontroller
keywords:
- jenkins-x
- exposecontroller
- expose
- ingress
maintainers:
- name: Pavels Veretennikovs
  email: Pavels.Veretennikovs@devops.care
