name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - buildpack

env:
  IMAGE_NAME: exposecontroller
  DOCKER_REGISTRY: ghcr.io
  DOCKER_REPOSITORY: DevopsCare/exposecontroller

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          builder: paketobuildpacks/builder:base
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
