name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - buildpack

env:
  IMAGE_NAME: exposecontroller
  DOCKER_REGISTRY: ghcr.io
  DOCKER_REPOSITORY: DevopsCare/exposecontroller

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pack
        run: |
          wget -qO- https://github.com/buildpacks/pack/releases/download/v0.23.1/pack-v0.23.1-linux.tgz | tar xvz -C /tmp
          sudo mv /tmp/pack /usr/local/bin

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          pack build ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest \
            --builder paketobuildpacks/builder:base \
            --publish
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}